### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by iAmYuhi** [inorilzy/renlian#3]
您好，请问您的opencv是多少版本的？执行face_train的        images, labels, face_num = load_dataset(self.path_name)方法抛异常ValueError: not enough values to unpack (expected 3, got 2)

**Comment by y158320** [comment]
opencv   3.3.1

**Comment by endluo** [comment]
ValueError: too many values to unpack (expected 2)，我也是遇到了这个问题怎么解决
